In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import pickle
from scipy.stats import bootstrap
from statsmodels.stats import proportion

import pysindy as ps

# Import Machine Scientist ODE
from importlib.machinery import SourceFileLoader

# Get the absolute path of the script's directory
script_dir = os.path.dirname(os.path.abspath("__file__"))
# Define the relative path to the module
relative_module_path = "../I-BMS-1d/machinescientist_ode.py"
path = os.path.join(script_dir, relative_module_path)
ms_ode = SourceFileLoader("ms_ode", path).load_module()

# Import Machine Scientist FIT
from importlib.machinery import SourceFileLoader

# Get the absolute path of the script's directory
script_dir = os.path.dirname(os.path.abspath("__file__"))
# Define the relative path to the module
relative_module_path = "../rguimera-machine-scientist/machinescientist.py"
path = os.path.join(script_dir, relative_module_path)
ms_fit = SourceFileLoader("ms_fit", path).load_module()

In [3]:
# files=[f for f in os.listdir('noise_data/')]
# print(files)
def get_nonzero_terms(model):
    nonzero_indices = np.nonzero(model.coefficients())[
        1
    ]  # Get indices of non-zero terms
    term_names = model.get_feature_names()  # Get feature names
    nonzero_terms = [term_names[i] for i in nonzero_indices]
    return nonzero_terms


def check_sindy_model(model):
    nonzero_terms = get_nonzero_terms(model)
    if nonzero_terms == ["B", "BB"] or nonzero_terms == ["B", "B^2"]:
        return True
    else:
        return False
sigmas = [
    0.005,
    0.006,
    0.007,
    0.008,
    0.009,
    0.01,
    0.02,
    0.03,
    0.04,
    0.05,
    0.06,
    0.07,
    0.08,
    0.09,
    0.1,
    0.2,
    0.3,
    0.4,
    0.5,
]
error_sampling_bms = []
error_sampling_fit = []
error_sampling_smooth = []
error_sampling_sindy = []
error_sampling_sindymod = []
error_sampling_bms_err = []
error_sampling_fit_err = []
error_sampling_smooth_err = []
error_sampling_sindy_err = []
error_sampling_sindymod_err = []
error_sampling_bms_bern_err = [[], []]
error_sampling_fit_bern_err = [[], []]
error_sampling_smooth_bern_err = [[], []]
error_sampling_sindy_bern_err = [[], []]
error_sampling_sindymod_bern_err = [[], []]
for sigma in sigmas:
    true_bms = []
    true_fit = []
    true_smooth = []
    true_sindy = []
    true_sindymod = []
    count = 0
    for i in range(0, 30):  # [34,38,39]:
        file = f"{sigma}_{i}.pkl"
        # BMS
        try:
            bms = None
            with open(
                f"./noise_data_res_exhaustive/BMS_{file[:-4]}.pkl", "rb"
            ) as f:
                # A new file will be created
                bms = pickle.load(f)
            if str(bms).strip() == "((_a0_ * B) + (_a1_ * (B ** 2)))".strip():
                true_bms.append(1.0)
            elif (
                str(bms).strip() == "((_a0_ + (_a1_ * B)) + (_a2_ * (B ** 2)))".strip()
                and bms.par_values["A0"]["_a0_"] < 0.01
            ):
                true_bms.append(1.0)
            else:
                print(
                    "IBMS true model not detected",file,
                    repr(str(bms)),
                    repr("((_a0_ * B) + (_a1_ * (B ** 2)))"),
                )
                true_bms.append(0.0)
            bms_fit = None
            with open(
                f"./noise_data_res_exhaustive/BMS_fit_{file[:-4]}.pkl", "rb"
            ) as f:
                # A new file will be created
                bms_fit = pickle.load(f)
            if str(bms_fit).strip() == "((_a0_ * B) + (_a1_ * (B ** 2)))".strip():
                true_fit.append(1.0)
            elif (
                str(bms_fit).strip()
                == "((_a0_ + (_a1_ * B)) + (_a2_ * (B ** 2)))".strip()
                and bms_fit.par_values["d0"]["_a0_"] < 0.01
            ):
                true_fit.append(1.0)
            else:
                print(
                    "FIT true model not detected",file,
                    repr(str(bms_fit)),
                    repr("((_a0_ * B) + (_a1_ * (B ** 2)))"),
                )
                true_fit.append(0.0)
            bms_smooth = None
            with open(
                f"./noise_data_res_exhaustive/BMS_smooth_{file[:-4]}.pkl", "rb"
            ) as f:
                # A new file will be created
                bms_smooth = pickle.load(f)
            if str(bms_smooth).strip() == "((_a0_ * B) + (_a1_ * (B ** 2)))".strip():
                true_smooth.append(1.0)
            elif (
                str(bms_smooth).strip()
                == "((_a0_ + (_a1_ * B)) + (_a2_ * (B ** 2)))".strip()
                and bms_smooth.par_values["A0"]["_a0_"] < 0.01
            ):
                true_smooth.append(1.0)
            else:
                print(
                    "SMOOTH true model not detected", file
                    repr(str(bms_smooth)),
                    repr("((_a0_ * B) + (_a1_ * (B ** 2)))"),
                )
                true_smooth.append(0.0)
            # Sindy
            data = pd.read_pickle(
                f"/export/home/oriolca/BMS_ODE/Logistic/noise_data/{file}"
            )

            # sindy_input=[data['x'].values.tolist(),data['y'].values.tolist()]
            X = data["B"].values
            time = data["t"].values

            ###############################################################################################
            # Weak sindy
            n_models = 1000
            library_functions = [
                lambda x: x,
                lambda x: x * x,
                lambda x: x * x * x,
                lambda x: x * x * x * x,
            ]
            library_function_names = [
                lambda x: x,
                lambda x: x + x,
                lambda x: x + x + x,
                lambda x: x + x + x + x,
            ]
            feature_names = ["B"]
            ensemble_optimizer = ps.STLSQ()

            weak_lib = ps.WeakPDELibrary(
                library_functions=library_functions,
                function_names=library_function_names,
                include_bias=True,
                spatiotemporal_grid=data.t.to_numpy(),
                is_uniform=True,
                K=1000,
            )

            # SINDy initialization
            model = ps.SINDy(
                feature_names=feature_names,
                feature_library=weak_lib,
                optimizer=ensemble_optimizer,
            )
            model.fit(X, ensemble=True, n_models=n_models, quiet=True)
            if check_sindy_model(model):
                true_sindy.append(1.0)
            else:
                true_sindy.append(0.0)
                print("Weak Sindy true model not detected",file, model.print())
            #####################################################################################################
            # Regurar sindy
            n_models = 1000
            ensemble_optimizer = ps.STLSQ()
            poly_library = ps.PolynomialLibrary(degree=4, include_bias=True)
            model = ps.SINDy(
                feature_names=["B"],
                feature_library=poly_library,
                optimizer=ensemble_optimizer,
            )
            dt = data.t[1] - data.t[0]
            model.fit(X, t=dt, ensemble=True, n_models=n_models, quiet=True)

            
            if check_sindy_model(model):
                true_sindymod.append(1.0)
            else:
                true_sindymod.append(0.0)
                print("Sindy true model not detected",file,model.print())
            count += 1.0
        except Exception as e:
            print(e)
            pass
    error_sampling_bms.append(np.mean(true_bms))
    error_sampling_bms_err.append(
        bootstrap(
            (true_bms,), np.mean, confidence_level=0.95, method="percentile"
        ).standard_error
    )
    error_sampling_fit.append(np.mean(true_fit))
    error_sampling_fit_err.append(
        bootstrap(
            (true_fit,),
            np.mean,
            confidence_level=0.95,
            random_state=1,
            method="percentile",
        ).standard_error
    )
    error_sampling_smooth.append(np.mean(true_smooth))
    error_sampling_smooth_err.append(
        bootstrap(
            (true_smooth,),
            np.mean,
            confidence_level=0.95,
            random_state=1,
            method="percentile",
        ).standard_error
    )
    error_sampling_sindy.append(np.mean(true_sindy))
    error_sampling_sindy_err.append(
        bootstrap(
            (true_sindy,),
            np.mean,
            confidence_level=0.95,
            random_state=1,
            method="percentile",
        ).standard_error
    )
    error_sampling_sindymod.append(np.mean(true_sindymod))
    error_sampling_sindymod_err.append(
        bootstrap(
            (true_sindymod,),
            np.mean,
            confidence_level=0.95,
            random_state=1,
            method="percentile",
        ).standard_error
    )

####################
0.005
((_a0_ * B) + (_a1_ * (B ** 2)))
BMS True
120
((_a0_ * B) + (_a1_ * (B ** 2)))
FIT True
((_a0_ * B) + (_a1_ * (B ** 2)))
SMOOTH True
(B)' = 0.832 B + -1.662 BBB + 0.835 BBBB
[[ 0.          0.8318204   0.         -1.66216622  0.83535602]]
Sindy False
(B)' = 0.980 B + -0.918 B^2 + -0.070 B^3
[[ 0.          0.97965149 -0.91821891 -0.06951828  0.        ]]
Sindy False
((_a0_ * B) + (_a1_ * (B ** 2)))
BMS True
120
((_a0_ * B) + (_a1_ * (B ** 2)))
FIT True
((_a0_ * B) + (_a1_ * (B ** 2)))
SMOOTH True
(B)' = 0.827 B + -1.653 BBB + 0.832 BBBB
[[ 0.          0.82682552  0.         -1.65298801  0.83236309]]
Sindy False
(B)' = 0.987 B + -0.958 B^2 + -0.030 B^3
[[ 0.          0.98679797 -0.95795821 -0.03012236  0.        ]]
Sindy False
((_a0_ * B) + (_a1_ * (B ** 2)))
BMS True
120
((_a0_ * B) + (_a1_ * (B ** 2)))
FIT True
((_a0_ * B) + (_a1_ * (B ** 2)))
SMOOTH True
(B)' = 0.823 B + -1.630 BBB + 0.810 BBBB
[[ 0.          0.82334623  0.         -1.62992155  0.81043202]]
S

In [3]:
data_store = {
    "sigmas": sigmas,
    "error_sampling_bms": error_sampling_bms,
    "error_sampling_fit": error_sampling_fit,
    "error_sampling_smooth": error_sampling_smooth,
    "error_sampling_wsindy": error_sampling_sindy,
    "error_sampling_intsindy": error_sampling_sindymod,
    "error_sampling_bms_err": error_sampling_bms_err,
    "error_sampling_fit_err": error_sampling_fit_err,
    "error_sampling_smooth_err": error_sampling_smooth_err,
    "error_sampling_wsindy_err": error_sampling_sindy_err,
    "error_sampling_intsindy_err": error_sampling_sindymod_err,
}
with open("detection_sigma.pkl", "wb") as file:
    pickle.dump(data_store, file=file)

In [4]:
error_sampling_bms = []
error_sampling_fit = []
error_sampling_smooth = []
error_sampling_sindy = []
error_sampling_sindymod = []
error_sampling_bms_err = []
error_sampling_fit_err = []
error_sampling_smooth_err = []
error_sampling_sindy_err = []
error_sampling_sindymod_err = []
error_sampling_bms_bern_err = [[], []]
error_sampling_fit_bern_err = [[], []]
error_sampling_smooth_bern_err = [[], []]
error_sampling_sindy_bern_err = [[], []]
error_sampling_sindymod_bern_err = [[], []]

size = list(range(30, 91, 10)) + list(range(100, 1001, 100))
for length in size:
    true_bms = []
    true_fit = []
    true_smooth = []
    true_sindy = []
    true_sindymod = []
    count = 0
    for i in range(0, 40):  # [34,38,39]:
        file = f"{i}_{length}.pkl"
        # BMS
        try:
            # BMS ODE
            with open(
                f"./noise_data_res_exhaustive/BMS_{file[:-4]}.pkl", "rb"
            ) as f:
                # A new file will be created
                bms = pickle.load(f)
            if str(bms) == "((_a0_ * B) + (_a1_ * (B ** 2)))":
                true_bms.append(1.0)
            else:
                print("IBMS true model not detected", file, bms)
                true_bms.append(0.0)
            # BMS Fit
            with open(
                f"./noise_data_res_exhaustive/BMS_fit_{file[:-4]}.pkl", "rb"
            ) as f:
                # A new file will be created
                bms_fit = pickle.load(f)
            if str(bms_fit) == "((_a0_ * B) + (_a1_ * (B ** 2)))":
                true_fit.append(1.0)
            else:
                print("FIT true model not detected", file, bms)
                true_fit.append(0.0)
            # BMS Smooth
            with open(
                f"./noise_data_res_exhaustive/BMS_smooth_{file[:-4]}.pkl", "rb"
            ) as f:
                # A new file will be created
                bms_smooth = pickle.load(f)
            if str(bms_smooth) == "((_a0_ * B) + (_a1_ * (B ** 2)))":
                true_smooth.append(1.0)
            else:
                print("SMOOTH true model not detected", file, bms)
                true_smooth.append(0.0)
            # Sindy
            data = pd.read_pickle(
                f"/export/home/oriolca/BMS_ODE/Logistic/noise_data_sigma0.05/{file}"
            )
            X = data["B"].values
            time = data["t"].values
            ###############################################################################################
            # Weak sindy
            n_models = 1000
            library_functions = [
                lambda x: x,
                lambda x: x * x,
                lambda x: x * x * x,
                lambda x: x * x * x * x,
            ]
            library_function_names = [
                lambda x: x,
                lambda x: x + x,
                lambda x: x + x + x,
                lambda x: x + x + x + x,
            ]
            feature_names = ["B"]
            ensemble_optimizer = ps.STLSQ()

            weak_lib = ps.WeakPDELibrary(
                library_functions=library_functions,
                function_names=library_function_names,
                include_bias=True,
                spatiotemporal_grid=data.t.to_numpy(),
                is_uniform=True,
                K=1000,
            )

            # SINDy initialization
            model = ps.SINDy(
                feature_names=feature_names,
                feature_library=weak_lib,
                optimizer=ensemble_optimizer,
            )
            model.fit(X, ensemble=True, n_models=n_models, quiet=True)
            if check_sindy_model(model):
                true_sindy.append(1.0)
            else:
                true_sindy.append(0.0)
                print("Weak Sindy true model not detected",file,model.print())
            #####################################################################################################
            # Regurar sindy
            n_models = 1000
            ensemble_optimizer = ps.STLSQ()
            poly_library = ps.PolynomialLibrary(degree=4, include_bias=True)
            model = ps.SINDy(
                feature_names=["B"],
                feature_library=poly_library,
                optimizer=ensemble_optimizer,
            )
            dt = data.t[1] - data.t[0]
            model.fit(X, t=dt, ensemble=True, n_models=n_models, quiet=True)
            
            if check_sindy_model(model):
                true_sindymod.append(1.0)
            else:
                true_sindymod.append(0.0)
                print("Sindy true model not detected",file,model.print())
            count += 1.0
        except Exception as e:
            print(e)
            pass
    error_sampling_bms.append(np.mean(true_bms))
    error_sampling_bms_err.append(
        bootstrap(
            (true_bms,), np.mean, confidence_level=0.95, method="percentile"
        ).standard_error
    )
    error_sampling_fit.append(np.mean(true_fit))
    error_sampling_fit_err.append(
        bootstrap(
            (true_fit,),
            np.mean,
            confidence_level=0.95,
            random_state=1,
            method="percentile",
        ).standard_error
    )
    error_sampling_smooth.append(np.mean(true_smooth))
    error_sampling_smooth_err.append(
        bootstrap(
            (true_smooth,),
            np.mean,
            confidence_level=0.95,
            random_state=1,
            method="percentile",
        ).standard_error
    )
    error_sampling_sindy.append(np.mean(true_sindy))
    error_sampling_sindy_err.append(
        bootstrap(
            (true_sindy,),
            np.mean,
            confidence_level=0.95,
            random_state=1,
            method="percentile",
        ).standard_error
    )
    error_sampling_sindymod.append(np.mean(true_sindymod))
    error_sampling_sindymod_err.append(
        bootstrap(
            (true_sindymod,),
            np.mean,
            confidence_level=0.95,
            random_state=1,
            method="percentile",
        ).standard_error
    )

####################
30
((_a0_ * B) + (_a1_ * (B ** 2)))
BMS True
_a0_
Fit False
((_a0_ * B) + (_a1_ * (B ** 2)))
Smooth True
(B)' = 1.016 B + -2.573 BBB + 1.560 BBBB
[[ 0.          1.01593231  0.         -2.57349539  1.55960607]]
Sindy False
(B)' = 1.483 B + -2.585 B^2 + 1.145 B^3
[[ 0.          1.48264545 -2.58467882  1.14547112  0.        ]]
Sindy False
((_a0_ * B) + (_a1_ * (B ** 2)))
BMS True
_a0_
Fit False
((_a0_ * B) + (_a1_ * (B ** 2)))
Smooth True
(B)' = 0.900 B + -2.280 BBB + 1.404 BBBB
[[ 0.          0.89956302  0.         -2.27988068  1.40425825]]
Sindy False
(B)' = 0.829 B + 0.259 B^2 + -2.613 B^3 + 1.535 B^4
[[ 0.          0.82896901  0.25877665 -2.61347398  1.53477288]]
Sindy False
((_a0_ * B) + (_a1_ * (B ** 2)))
BMS True
_a0_
Fit False
_a0_
Smooth False
(B)' = 0.779 B + -1.409 BBB + 0.603 BBBB
[[ 0.          0.77916779  0.         -1.40935894  0.60310032]]
Sindy False
(B)' = 0.712 B + -1.072 B^3 + 0.307 B^4
[[ 0.          0.71222146  0.         -1.07237674  0.30661906]

In [5]:
data_store = {
    "size": size,
    "error_sampling_bms": error_sampling_bms,
    "error_sampling_fit": error_sampling_fit,
    "error_sampling_smooth": error_sampling_smooth,
    "error_sampling_wsindy": error_sampling_sindy,
    "error_sampling_intsindy": error_sampling_sindymod,
    "error_sampling_bms_err": error_sampling_bms_err,
    "error_sampling_fit_err": error_sampling_fit_err,
    "error_sampling_smooth_err": error_sampling_smooth_err,
    "error_sampling_wsindy_err": error_sampling_sindy_err,
    "error_sampling_intsindy_err": error_sampling_sindymod_err,
}
with open("detection_length.pkl", "wb") as file:
    pickle.dump(data_store, file=file)